// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYsSwdCELUJgfYyyZbhw6X2Y8YDfOjwNM',
    appId: '1:28801310453:web:64be4c87b9ca97f90f6fbc',
    messagingSenderId: '28801310453',
    projectId: 'conquera-fcdef',
    authDomain: 'conquera-fcdef.firebaseapp.com',
    storageBucket: 'conquera-fcdef.firebasestorage.app',
    measurementId: 'G-TW2806QGBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEaBDkLBdYRH1l_7Zq_PNh6nqP26nXz44',
    appId: '1:28801310453:android:116d444de9f1a34a0f6fbc',
    messagingSenderId: '28801310453',
    projectId: 'conquera-fcdef',
    storageBucket: 'conquera-fcdef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLSkZp0G2OubouUTwz5kWm2tI2VQYRskM',
    appId: '1:28801310453:ios:b4779f0983d463f40f6fbc',
    messagingSenderId: '28801310453',
    projectId: 'conquera-fcdef',
    storageBucket: 'conquera-fcdef.firebasestorage.app',
    iosBundleId: 'com.example.conquera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLSkZp0G2OubouUTwz5kWm2tI2VQYRskM',
    appId: '1:28801310453:ios:b4779f0983d463f40f6fbc',
    messagingSenderId: '28801310453',
    projectId: 'conquera-fcdef',
    storageBucket: 'conquera-fcdef.firebasestorage.app',
    iosBundleId: 'com.example.conquera',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYsSwdCELUJgfYyyZbhw6X2Y8YDfOjwNM',
    appId: '1:28801310453:web:e319b7de2ef1ce350f6fbc',
    messagingSenderId: '28801310453',
    projectId: 'conquera-fcdef',
    authDomain: 'conquera-fcdef.firebaseapp.com',
    storageBucket: 'conquera-fcdef.firebasestorage.app',
    measurementId: 'G-VVRYGYJSN9',
  );
}
