import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

import 'firebase_options.dart'; // generated by `flutterfire configure`
import 'screens/home_screen.dart';
import 'theme/conquera_theme.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Anonymous auth gives every player a stable uid (used as the
  // players/ doc id and provinces.ownerId) without a login screen yet.
  if (FirebaseAuth.instance.currentUser == null) {
    await FirebaseAuth.instance.signInAnonymously();
  }
  debugPrint('Signed in anonymously: ${FirebaseAuth.instance.currentUser!.uid}');

  runApp(const ConqueraApp());
}

class ConqueraApp extends StatelessWidget {
  const ConqueraApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Conquera',
      debugShowCheckedModeBanner: false,
      theme: buildConqueraTheme(),
      home: const HomeScreen(),
    );
  }
}