import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

import 'firebase_options.dart'; // generated by `flutterfire configure`
import 'screens/map_screen.dart';
import 'services/firestore_service.dart';
import 'theme/conquera_theme.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Anonymous auth gives every player a stable uid (used as the
  // players/ doc id and provinces.ownerId) without a login screen yet.
  if (FirebaseAuth.instance.currentUser == null) {
    await FirebaseAuth.instance.signInAnonymously();
  }
  final uid = FirebaseAuth.instance.currentUser!.uid;
  debugPrint('Signed in anonymously: $uid');

  // Make sure the shared game and this player's document exist.
  await FirestoreService().ensureJoined(
    gameId: FirestoreService.defaultGameId,
    uid: uid,
  );
  debugPrint('Joined game ${FirestoreService.defaultGameId} as $uid');

  runApp(const ConqueraApp());
}

class ConqueraApp extends StatelessWidget {
  const ConqueraApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Conquera',
      debugShowCheckedModeBanner: false,
      theme: buildConqueraTheme(),
      home: const MapScreen(),
    );
  }
}