/// Island countries have no land border, so these pairs are treated as
/// bordering across the water. Each pair works both ways. Use the same ISO
/// alpha-2 ids as the SVG; a pair with an id that isn't on the map is
/// skipped (and printed in the debug console), so it's safe to add more.
const List<(String, String)> seaLinks = [
  // East & South-East Asia
  ('JP', 'KR'),
  ('JP', 'RU'),
  ('JP', 'TW'),
  ('TW', 'CN'),
  ('TW', 'PH'),
  ('PH', 'MY'),
  ('PH', 'ID'),
  ('ID', 'SG'),
  ('SG', 'MY'),
  ('ID', 'AU'),
  ('RU', 'US'),
  // South Asia & Gulf
  ('LK', 'IN'),
  ('LK', 'MV'),
  ('MV', 'IN'),
  ('BH', 'SA'),
  ('BH', 'QA'),
  // Oceania
  ('AU', 'PG'),
  ('AU', 'NZ'),
  ('AU', 'NC'),
  ('PG', 'SB'),
  ('SB', 'VU'),
  ('VU', 'NC'),
  ('VU', 'FJ'),
  ('FJ', 'TO'),
  ('FJ', 'WS'),
  ('WS', 'TO'),
  ('WS', 'AS'),
  // Mediterranean & Europe
  ('CY', 'TR'),
  ('CY', 'SY'),
  ('CY', 'LB'),
  ('CY', 'IL'),
  ('MT', 'IT'),
  ('MT', 'TN'),
  ('MT', 'LY'),
  ('IT', 'TN'),
  ('IT', 'HR'),
  ('IT', 'FR'),
  ('GR', 'TR'),
  ('GR', 'IT'),
  ('ES', 'MA'),
  ('ES', 'DZ'),
  ('GB', 'FR'),
  ('GB', 'IE'),
  ('DK', 'SE'),
  ('DK', 'NO'),
  // North Atlantic
  ('IS', 'GL'),
  ('IS', 'NO'),
  ('IS', 'FO'),
  ('FO', 'GB'),
  ('FO', 'NO'),
  ('GL', 'CA'),
  // Caribbean
  ('CU', 'US'),
  ('CU', 'HT'),
  ('CU', 'JM'),
  ('CU', 'BS'),
  ('CU', 'MX'),
  ('CU', 'KY'),
  ('JM', 'HT'),
  ('JM', 'KY'),
  ('DO', 'PR'),
  ('PR', 'VI'),
  ('BS', 'US'),
  ('BS', 'TC'),
  ('TT', 'VE'),
  // Africa & Indian Ocean
  ('MG', 'MZ'),
  ('MG', 'KM'),
  ('MG', 'MU'),
  ('MG', 'SC'),
  ('KM', 'MZ'),
  ('KM', 'TZ'),
  ('CV', 'SN'),
  ('CV', 'MR'),
  ('ST', 'GA'),
  ('ST', 'GQ'),
  // South Atlantic
  ('FK', 'AR'),
];